blank_issues_enabled: false
contact_links:
  - name: â“ Ask a Question
    url: https://github.com/Sour-abh-Raj/lucifer-dev/discussions/categories/q-a
    about: Ask and answer lucifer-dev related questions.
  - name: ğŸ“– Read the documentation
    url: https://github.com/Sour-abh-Raj/lucifer-dev/blob/master/README.md
    about: Please consult the documentation before opening any issues!
